department_app/views/department.py
from flask import Blueprint, render_template, request, redirect
from department_app.rest.department import DepartmentResource
from werkzeug.exceptions import BadRequest, Conflict, NotFound

bp = Blueprint("department", __name__)


@bp.route("/edit_department", methods=["GET"])
def get_edit_department():
    """
    Function for handling get requests to change department
    :return: render template to edit department
    """
    department_name = request.args.get("name")
    try:
        department = DepartmentResource(name=department_name).get().get_json()
    except (BadRequest, NotFound):
        return render_template("errors.html", code=400,
                               message="Please chose department to edit!")
    return render_template("edit_department.html", department=department)


@bp.route("/create_department", methods=["GET"])
def get_create_department():
    """
    Function to handle get request for create departments
    :return: render template
    """
    return render_template("create_department.html")


@bp.route("/edit_department", methods=["POST"])
def edit_department():
    """
    Function to handle changes in departments
    :return: back to main page if all is correct
    """
    name = request.form["name"]
    address = request.form["address"]
    try:
        DepartmentResource(name=name, address=address).put()
    except (BadRequest, Conflict) as error:
        department = {"name": name, "address": address}
        return render_template("edit_department.html", department=department,
                               error=error.data.get(
                                   "message") or "Please correct values!")
    return redirect("/")


@bp.route("/create_department", methods=["POST"])
def create_department():
    """
    Function to handle creation department
    :return: back to main page if all is correct
    """
    name = request.form["name"]
    address = request.form["address"]
    try:
        DepartmentResource(name=name, address=address).post()
    except (BadRequest, Conflict) as error:
        return render_template("create_department.html",
                               error=error.data.get(
                                   "message") or "Please correct values!")
    return redirect("/")

department_app/views/departments.py
from flask import Blueprint, redirect, render_template, url_for, request
from department_app.rest.departments import DepartmentsResource
from department_app.rest.department import DepartmentResource
from werkzeug.exceptions import Conflict


bp = Blueprint("departments", __name__)


@bp.route("/", methods=["GET"])
@bp.route("/departments", methods=["GET", "POST"])
def get_departments():
    """
    Function for handling get request to departments
    :return: render template
    """
    search = request.form.get("search_name")
    result_json = DepartmentsResource(search_name=search).get().get_json()
    return render_template("departments.html", result=result_json)


@bp.route("/departments/delete", methods=["POST"])
def delete_department():
    """
    Function for handling department delete
    :return: redirect to department page
    """
    name = request.form['name']
    if not name:
        return render_template("errors.html",
                               code=404,
                               message="ERROR Department name should be given!")
    try:
        DepartmentResource(name=name).delete()
    except Conflict:
        return render_template("errors.html", code=409,
                               message="There are employees in such department."
                                       " You cannot delete it!")
    return redirect(url_for("departments.get_departments"))

department_app/views/employee.py
from flask import Blueprint, redirect, render_template, request, url_for
from department_app.models.models import Department
from werkzeug.exceptions import BadRequest, Conflict, NotFound
from department_app.rest.employee import EmployeeResource

bp = Blueprint("employee", __name__)


@bp.route("/edit_employee", methods=["GET"])
def get_edit_employee():
    """
    Function to handle get request for edit employee
    :return: redirect to employees page
    """
    id_ = request.args.get("id")
    try:
        employee = EmployeeResource(id_=int(id_)).get().get_json()
        departments = Department.query.with_entities(Department.name)
    except (ValueError, BadRequest, NotFound):
        return render_template("errors.html", code=400, message="You should "
                                                                "give "
                                                                "correct id of "
                                                                "employee!")
    return render_template("edit_employee.html", employee=employee,
                           departments=departments)


@bp.route("/edit_employee", methods=["POST"])
def edit_employee():
    """
    Function for handling post request for edit employee
    :return: redirect to employees page
    """
    id_ = request.form["id"]
    first_name = request.form["first_name"]
    last_name = request.form["last_name"]
    department_name = request.form["department_name"]
    date_of_birth = request.form["date_of_birth"]
    salary = request.form["salary"]
    employee = {
        "id_": int(id_),
        "first_name": first_name,
        "last_name": last_name,
        "department_name": department_name,
        "date_of_birth": date_of_birth,
        "salary": salary
    }
    try:
        EmployeeResource(**employee).put()
    except (BadRequest, Conflict, NotFound) as error:
        # Always need departments for select option
        departments = Department.query.with_entities(Department.name)
        return render_template(
            "edit_employee.html",
            employee=employee,
            departments=departments,
            error=error.data.get("message") or "Please correct values!"
        )
    return redirect(url_for("employees.get_employees"))


@bp.route("/create_employee", methods=["GET"])
def get_create_employee():
    """
    Function for handling get request to form create employee
    :return:
    """
    departments = Department.query.with_entities(Department.name)
    return render_template("create_employee.html", departments=departments)


@bp.route("/create_employee", methods=["POST"])
def create_employee():
    """
    Function for handling post requests to create new emploee
    :return: redirect to employees page
    """
    first_name = request.form["first_name"]
    last_name = request.form["last_name"]
    department_name = request.form["department_name"]
    date_of_birth = request.form["date_of_birth"]
    salary = request.form["salary"]
    try:
        EmployeeResource(
            first_name=first_name,
            last_name=last_name,
            department_name=department_name,
            date_of_birth=date_of_birth,
            salary=salary).post()
    except (BadRequest, Conflict, NotFound) as error:
        # Always need departments for select option
        departments = Department.query.with_entities(Department.name)
        return render_template(
            "create_employee.html",
            departments=departments,
            error=error.data.get("message") or "Please correct values!"
        )
    return redirect(url_for("employees.get_employees"))

department_app/views/employees.py
from flask import Blueprint, render_template, request, redirect, url_for
from department_app.rest.employees import EmployeesResource
from department_app.rest.employee import EmployeeResource

bp = Blueprint("employees", __name__)


@bp.route("/employees", methods=["GET", "POST"])
def get_employees():
    """
    Function for handling get employees requests
    :return: render template
    """
    begin_date = request.form.get("begin_date")
    end_date = request.form.get("end_date")
    result_json = EmployeesResource(
        request.args.get("department_name"), begin_date=begin_date,
        end_date=end_date).get().get_json()
    return render_template("employees.html", result=result_json)


@bp.route("/employees/delete", methods=["POST"])
def delete_employee():
    """
    Delete employee from database
    :return: redirect to employees page
    """
    id_ = request.form["id"]
    if not id_:
        render_template(
            "errors.html",
            code=404,
            message="Id of the employee should be given"
        )
    try:
        id_ = int(id_)
        EmployeeResource(id_=id_).delete()
    except ValueError:
        return render_template("errors.html", code=404,
                               message="Error! Cannot delete employee!")
    return redirect(url_for("employees.get_employees"))

department_app/templates/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet"
          href="{{ url_for('static', filename='css/basic.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <h1>University Departments</h1>
        <nav>
            <div class = "nav">
                <a
                   href="{{ url_for('departments.get_departments') }}">
                    Departments</a>
            </div>
            <div class = "nav">
                <a href=" {{ url_for('employees.get_employees' )}}">Employees
                </a>
            </div>
            {% block search %} {% endblock %}
        </nav>
    </header>
    <main>
        {% block main %} {% endblock %}
    </main>
</body>
</html>

department_app/templates/create_department.html
{% extends 'basic.html' %}

{% block title %}Add department - University Departments{% endblock %}

{% block main %}
    <div class="edit">
        <p style="color: red; font-weight: bold; font-size: 1.5em;">{{ error }}</p>
        <form action="/create_department" method="post">
            <p class="form_title">Add department</p>
            <div class="form_element">
                <label for="department_name">Department name:</label>
                <input type="text" id="department_name" name="name" required>
            </div>
            <div class="form_element">
                <label for="department_address">Department address:</label>
                <input type="text" id="department_address" name="address" required>
            </div>
            <div class="form_buttons">
                <a href="{{ url_for('departments.get_departments') }}"><input type="button" id="cancel"
                                                                             value="Cancel"></a>
                <input type="submit" id="save" value="Save">
            </div>

        </form>
    </div>
{% endblock %}

department_app/templates/create_employee.html
{% extends 'basic.html' %}

{% block title %}Add employee - University Departments{% endblock %}

{% block main %}
        <div class="edit">
            <p style="color: red; font-weight: bold; font-size: 1.5em;">{{ error }}</p>
            <form method="post" action="/create_employee">
                <p class="form_title">Add employee</p>
                <div class="form_element">
                    <label for="first_name">First name:</label>
                    <input type="text" name="first_name" id="first_name" required>
                </div>
                <div class="form_element">
                    <label for="last_name">Last name:</label>
                    <input type="text" name="last_name" id="last_name" required>
                </div>
                <div class="form_element">
                    <label for="department_name">Department name:</label>
                    <select name="department_name" id="department_name" required>
                        {% for department in departments %}
                            <option value="{{ department.name}}">{{ department.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form_element">
                    <label for="birth_date">Date of birth:</label>
                    <input type="date" name="date_of_birth" id="birth_date" required>
                </div>
                <div class="form_element">
                    <label for="salary">Salary:</label>
                    <input type="number" id="salary" name="salary" min=0 required>
                </div>
                <div class="form_buttons">
                    <a href="{{ url_for('employees.get_employees') }}">
                        <input type="button" id="cancel" value="Cancel">
                    </a>
                    <input type="submit" id="save" value="Save">
                </div>

            </form>
        </div>
{% endblock %}

department_app/templates/departments.html
{% extends 'basic.html' %}

{% block title %}Departments - University Departments{% endblock %}

{% block search %}
    <form action="departments" method="post">
        <input type="text" name="search_name" placeholder="Search...">
        <button type="submit" id="search"><i class="fa fa-search"></i></button>
    </form>
{% endblock %}

{% block main %}
    {% if result %}
        <table>
            <thead>
            <tr>
                <td>Department name</td>
                <td>Department address</td>
                <td>Number of employees</td>
                <td>Average salary</td>
                <td colspan="2">
                    <button type="button" id="add_button">
                        <a href= "{{ url_for('department.create_department') }}">Add department</a>
                    </button>
                </td>
            </tr>
            </thead>
            {% for department in result %}
            <tbody>
            <tr>
                <td><a href="{{ url_for('employees.get_employees', department_name=department.name) }}">
                    {{ department.name }}</a></td>
                <td>{{ department.address}}</td>
                <td>{{ department.count_employees}}</td>
                <td>{{ department.avg_salary}}</td>
                <td>
                    <a href="{{ url_for('department.edit_department', name=department.name) }}">
                        <button type="button" class="edit_button">
                            <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                        </button>
                    </a>
                </td>
                <td>
                    <form method="post" action="departments/delete" onsubmit="return confirm('Please confirm delete');">
                            <input type="hidden" name="name" value="{{department.name}}">
                            <button type="submit" class="delete_button">
                                <i class="fa fa-times" aria-hidden="true"></i>
                            </button>
                    </form>

                </td>
            </tr>
            </tbody>
            {% endfor %}
        </table>
    {% else %}
        <h2>There are no departments in the app</h2>
    {% endif%}
{% endblock %}

department_app/templates/edit_department.html
{% extends 'basic.html' %}

{% block title %}Edit department - University Departments{% endblock %}

{% block main %}
    <div class="edit">
        <p style="color: red; font-weight: bold; font-size: 1.5em;">{{ error }}</p>
        <form action="/edit_department" method="post">
            <p class="form_title">Edit department</p>
            <div class="form_element">
                <label for="department_name">Department name:</label>
                <input type="text" id="department_name" name="name" value="{{ department.name }}" readonly="readonly">
            </div>
            <div class="form_element">
                <label for="department_address">Department address:</label>
                <input type="text" id="department_address" name="address" value="{{ department.address }}" required>
            </div>
            <div class="form_buttons">
                <a href="{{ url_for('departments.get_departments') }}"><input type="button" id="cancel"
                                                                             value="Cancel"></a>
                <input type="submit" id="save" value="Save">
            </div>

        </form>
    </div>
{% endblock %}

department_app/templates/edit_employee.html
{% extends 'basic.html' %}

{% block title %}Edit employee - University Departments{% endblock %}

{% block main %}
        <div class="edit">
            <p style="color: red; font-weight: bold; font-size: 1.5em;">{{ error }}</p>
            <form method="post" action="/edit_employee">
                <input type="hidden" name="id" value="{{ employee.id }}">
                <p class="form_title">Edit employee</p>
                <div class="form_element">
                    <label for="first_name">First name:</label>
                    <input type="text" name="first_name" id="first_name" value="{{ employee.first_name }}" required>
                </div>
                <div class="form_element">
                    <label for="last_name">Last name:</label>
                    <input type="text" id="last_name" name="last_name" value="{{ employee.last_name }}" required>
                </div>
                <div class="form_element">
                    <label for="department_name">Department name:</label>
                    <select name="department_name" id="department_name" required>
                        {% for department in departments %}
                            {% if department.name == employee.department_name %}
                                <option value="{{ department.name}}" selected="selected">{{ department.name }}</option>
                            {% else %}
                                <option value="{{ department.name}}">{{ department.name }}</option>
                            {% endif %}

                        {% endfor %}
                    </select>
                </div>
                <div class="form_element">
                    <label for="birth_date">Date of birth:</label>
                    <input type="date" id="birth_date" name="date_of_birth"
                           value="{{ employee.date_of_birth}}" required>
                </div>
                <div class="form_element">
                    <label for="salary">Salary:</label>
                    <input type="number" id="salary" name="salary" min=0 value="{{ employee.salary }}" required>
                </div>
                <div class="form_buttons">
                    <a href="{{ url_for('employees.get_employees') }}">
                        <input type="button" id="cancel" value="Cancel">
                    </a>
                    <input type="submit" id="save" value="Save">
                </div>

            </form>
        </div>
{% endblock %}

department_app/templates/employees.html
{% extends 'basic.html' %}

{% block title %}Employees - University Departments {% endblock %}

{% block search %}
    <form action="/employees" method="post">
        <label for="begin_date">Start date:</label>
        <input type="date" name="begin_date" id="begin_date">
        <label for="end_date">End date:</label>
        <input type="date" name="end_date" id="end_date">
        <button type="submit" id="date_search"><i class="fa fa-search"></i></button>
    </form>
{% endblock %}


{% block main %}
    {% if result %}
        <table>
            <thead>
                <tr>
                    <td>First name</td>
                    <td>Last name</td>
                    <td>Department name</td>
                    <td>Date of birth</td>
                    <td>Salary</td>
                    <td colspan="2">
                        <button type="button" id="add_button">
                            <a href = "{{ url_for('employee.get_create_employee') }}">Add employee</a>
                        </button>
                    </td>
                </tr>
            </thead>
            <tbody>
                {% for employee in result %}
                    <tr>
                        <td>{{ employee.first_name }}</td>
                        <td>{{ employee.last_name }}</td>
                        <td>{{ employee.department_name }}</td>
                        <td>{{ employee.date_of_birth }}</td>
                        <td>{{ employee.salary }}</td>
                        <td>
                            <a href="{{ url_for('employee.get_edit_employee', id=employee.id) }}">
                                <button type="button" class="edit_button">
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                </button>
                            </a>
                        </td>
                        <td>
                            <form method="post" action="employees/delete"
                                  onsubmit="return confirm('Please confirm delete');">
                                    <input type="hidden" name="id" value="{{ employee.id }}">
                                    <button type="submit" class="delete_button">
                                        <i class="fa fa-times" aria-hidden="true"></i>
                                    </button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h2>There are no such employees in the app</h2>
    {% endif%}
{% endblock %}

department_app/templates/errors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ERROR {{ code }}!</title>
</head>
<body>
    <h1>ERROR {{ code }}</h1>
    <h2>{{ message }}</h2>
</body>
</html>